[package]
authors = ['Substrate DevHub <https://github.com/phuquocdog>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://phuquoc.dog'
license = 'Unlicense'
name = 'phuquocdog'
repository = 'https://github.com/phuquocdog/node'
version = '3.0.0'

[[bin]]
name = 'phuquocdog'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05'}

[dependencies]
jsonrpc-core = '15.1.0'
structopt = '0.3.8'
hex-literal= '0.3.1'

# Substrate dependencies
frame-benchmarking = {  git = "https://github.com/paritytech/substrate", branch = "master" }
frame-support = {  git = "https://github.com/paritytech/substrate", branch = "master" }
frame-benchmarking-cli = {  git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-im-online = {  git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-staking = {  git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment-rpc = {  git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-contracts = {  git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-contracts-rpc = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-chain-spec = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-sync-state-rpc = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-slots = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-uncles = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-authority-discovery = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-babe = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-babe-rpc = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-epochs = {  git = "https://github.com/paritytech/substrate", branch = "master" }
grandpa = {  git = "https://github.com/paritytech/substrate", branch = "master" ,package="sc-finality-grandpa"}
sc-finality-grandpa-rpc = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-keystore = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc-api = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-api = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-authorship = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-block-builder = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-babe = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keystore = {  git = "https://github.com/paritytech/substrate", branch = "master" }
grandpa-primitives = {  git = "https://github.com/paritytech/substrate", branch = "master" , package="sp-finality-grandpa"}
sp-inherents = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-timestamp = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-telemetry = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = {  git = "https://github.com/paritytech/substrate", branch = "master" }
substrate-frame-rpc-system = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service-test = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keyring = {  git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = {  git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool-api = {  git = "https://github.com/paritytech/substrate", branch = "master" }
sp-authority-discovery = {  git = "https://github.com/paritytech/substrate", branch = "master" }

# local dependencies
phuquocdog-runtime = {version = '3.0.0', path = '../runtime'}

[features]
default = []
runtime-benchmarks = ['phuquocdog-runtime/runtime-benchmarks']
